spring:
  datasource:
    url: jdbc:h2:mem:pets;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # or 'create' while you’re developing
      defer-datasource-initialization: true
sql:
  init:
    mode: always            # run data.sql in dev even with embedded DB
management:
  endpoints:
    web:
      exposure:
        include: health,info